const { words } = require("./words");

const todaysWord = words[Math.floor(new Date().setHours(0, 0, 0, 0) / 8.64e7) % words.length];

module.exports = {
  title: "Trumple",
  answerWord: todaysWord.toUpperCase(),
  gameNumber: words.indexOf(todaysWord),
  maxGuesses: 6,
  wordLength: 5,
  gridGap: 5,
  tileSize: 52,
  flipAnimationDurationMS: 600,
  flipAnimationDelay: 400,
  winAnimationDurationMS: 350,
  winAnimationDelay: 75,
  letters: [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ],
  keyboardLetters: [
    ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
    ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
    ["Z", "X", "C", "V", "B", "N", "M"],
  ],
  colors: {
    correct: "#40916c",
    present: "#f9c74f",
    absent: "#8b8c89",
    unguessed: "#d3d6da",
  },
  emojiMap: {
    "#40916c": "🟩",
    "#f9c74f": "🟨",
    "#8b8c89": "⬛",
  },
  version: 1.2,
};
